slack:
  # channel to send build notifications to and allow /slash commands from
  channel: '#test'
  # message template to use for build status
  # see templates/README.md
  templates:
    default: 'default.json'
    working: 'working.json'
    failure: 'failure.json'
  webhook:
    # (Optional) The maximum Content-Length of webhook from slack in bytes (Defaults to 50kb)
    max_content_length: 50000
gcloud:
  # GCP Project with CloudBuild
  project_id: 'my-project'
  # GCS bucket to store slackbuild source in
  gcs_bucket_url: 'my-bucket'
# only used to generate links to revisions for message templates
# base url to your account/orgaization where repos with cloudbuilds live
github_url: 'https://github.com/you'
